### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by iwashi** [wada3108/flutter-calculator-app#1]
@wada3108 
didChangeAppLifecycleState など含め、授業で触れていない点も独自に実装されており、大変素晴らしかったと思います。課題提出お疲れさまでした！

本IssueはいつでもcloseいただいてOKです。

**Comment by wada3108** [comment]
課題をご確認いただき、ありがとうございました。

また、冬クォーターの間、授業では大変お世話になりました。
Flutterの利用方法はもちろん、今後の学習の仕方なども教えていただき、
大変参考になりました。重ねてお礼申し上げます。

今日から早速、AtCoderの勉強を始めてみたところです。
なかなか難しい問題が多いですが、頑張って進めて行けたらと思っています。
